language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
  - '6'
  - '4'
before_install:
  - npm i -g npm@3.10.9 && npm i -g yarn --cache-min 999999999
install:
  - yarn
script:
  - echo 'Done' # 'npm run prepublish is done by installer'
